server:
  port: 8080
  host: localhost
  enviroment: dev
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: tudo-thrifting
  max_idle_cons: 10 # max idle connections
  max_open_cons: 100 # max open connections
  con_max_life_time: 3600 # connection max lifetime
redis:
  host: 127.0.0.1
  port: 6379
  password:
  datbase: 0
  pool_size: 10
logger:
  file_name: "./storage/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
  log_level: debug
