name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Deploy to server via SSH and perform multiple steps
      - name: Deploy and build on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Step 1: Navigate to the project folder
            cd ~/tudo-thrfting-clothes-server

            # Step 2: Pull latest changes from the Git repository
            git pull

            # Step 4: Rebuild and start docker containers
            docker-compose up --build -d
